-- Durable, retryable deletion orchestration. This migration intentionally does
-- not schedule or invoke the worker: deploying admin-manage-user is a separate
-- rollout gate.

CREATE TABLE public.user_deletion_jobs (
  -- A target has exactly one lifetime deletion job, so using the target UUID as
  -- the job UUID lets the audited Edge handler identify it before the atomic
  -- begin RPC mutates anything.
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  target_user_id UUID NOT NULL,
  requested_by UUID NOT NULL,
  status TEXT NOT NULL DEFAULT 'requested'
    CHECK (status IN (
      'requested',
      'cleaning_storage',
      'deleting_auth',
      'retryable_error',
      'manual_review',
      'completed'
    )),
  resume_status TEXT
    CHECK (resume_status IS NULL OR resume_status IN ('cleaning_storage', 'deleting_auth')),
  lease_token UUID,
  lease_expires_at TIMESTAMPTZ,
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  removed_object_count BIGINT NOT NULL DEFAULT 0 CHECK (removed_object_count >= 0),
  last_error_code TEXT,
  last_error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  UNIQUE (target_user_id),
  CHECK ((lease_token IS NULL) = (lease_expires_at IS NULL)),
  CHECK ((status = 'completed') = (completed_at IS NOT NULL)),
  CHECK (status = 'retryable_error' OR resume_status IS NULL)
);

CREATE TABLE public.user_deletion_bucket_progress (
  job_id UUID NOT NULL REFERENCES public.user_deletion_jobs(id) ON DELETE CASCADE,
  bucket_id TEXT NOT NULL
    CHECK (bucket_id IN ('chat-images', 'check-in-photos', 'meal-photos')),
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'cleaning', 'clean')),
  removed_object_count BIGINT NOT NULL DEFAULT 0 CHECK (removed_object_count >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (job_id, bucket_id)
);

CREATE TABLE public.user_deletion_prefix_work (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id UUID NOT NULL REFERENCES public.user_deletion_jobs(id) ON DELETE CASCADE,
  bucket_id TEXT NOT NULL,
  prefix TEXT NOT NULL CHECK (length(prefix) BETWEEN 1 AND 1024),
  depth INTEGER NOT NULL CHECK (depth >= 0),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'complete')),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (job_id, bucket_id, prefix),
  FOREIGN KEY (job_id, bucket_id)
    REFERENCES public.user_deletion_bucket_progress(job_id, bucket_id)
    ON DELETE CASCADE
);

CREATE INDEX user_deletion_jobs_status_idx
  ON public.user_deletion_jobs(status, updated_at);
CREATE INDEX user_deletion_prefix_pending_idx
  ON public.user_deletion_prefix_work(job_id, bucket_id, depth DESC, id)
  WHERE status = 'pending';

ALTER TABLE public.user_deletion_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_deletion_jobs FORCE ROW LEVEL SECURITY;
ALTER TABLE public.user_deletion_bucket_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_deletion_bucket_progress FORCE ROW LEVEL SECURITY;
ALTER TABLE public.user_deletion_prefix_work ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_deletion_prefix_work FORCE ROW LEVEL SECURITY;

-- Human admins may observe durable job state. public.get_is_admin() is upgraded
-- to require AAL2 by the preceding MFA-enforcement stage.
CREATE POLICY "AAL2 admins read user deletion jobs"
  ON public.user_deletion_jobs FOR SELECT TO authenticated
  USING ((SELECT public.get_is_admin()));

CREATE POLICY "AAL2 admins read user deletion bucket progress"
  ON public.user_deletion_bucket_progress FOR SELECT TO authenticated
  USING ((SELECT public.get_is_admin()));

REVOKE ALL ON public.user_deletion_jobs FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.user_deletion_bucket_progress FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.user_deletion_prefix_work FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.user_deletion_jobs TO authenticated;
GRANT SELECT ON public.user_deletion_bucket_progress TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_deletion_jobs TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_deletion_bucket_progress TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_deletion_prefix_work TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.user_deletion_prefix_work_id_seq TO service_role;

CREATE OR REPLACE FUNCTION private.protect_user_deletion_job_identity()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  IF NEW.id IS DISTINCT FROM OLD.id
     OR NEW.target_user_id IS DISTINCT FROM OLD.target_user_id
     OR NEW.requested_by IS DISTINCT FROM OLD.requested_by
     OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
    RAISE EXCEPTION 'Deletion job identity is immutable' USING ERRCODE = '23514';
  END IF;
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.protect_user_deletion_job_identity() FROM PUBLIC;

CREATE TRIGGER protect_user_deletion_job_identity
BEFORE UPDATE ON public.user_deletion_jobs
FOR EACH ROW EXECUTE FUNCTION private.protect_user_deletion_job_identity();

CREATE OR REPLACE FUNCTION private.keep_deletion_targets_blocked()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF OLD.is_blocked = true
     AND NEW.is_blocked = false
     AND EXISTS (
       SELECT 1
       FROM public.user_deletion_jobs
       WHERE target_user_id = NEW.id
         AND status <> 'completed'
     ) THEN
    RAISE EXCEPTION 'User has an active deletion job' USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.keep_deletion_targets_blocked() FROM PUBLIC;

CREATE TRIGGER keep_deletion_targets_blocked
BEFORE UPDATE OF is_blocked ON public.profiles
FOR EACH ROW EXECUTE FUNCTION private.keep_deletion_targets_blocked();

-- Storage writes take a transaction-scoped shared lock for the user identified
-- by the managed prefix (falling back to owner_id). The deletion begin RPC
-- takes the matching exclusive lock before blocking the profile. Therefore an
-- upload already in progress commits before cleanup starts, while a later
-- upload waits and then observes the blocked/missing profile.
CREATE OR REPLACE FUNCTION private.lock_deletion_storage_write(
  p_name TEXT,
  p_owner_id TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_prefix TEXT := split_part(COALESCE(p_name, ''), '/', 1);
  v_actor_user_id UUID := auth.uid();
  v_target_user_id UUID;
  v_unblocked BOOLEAN;
BEGIN
  IF v_prefix ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' THEN
    v_target_user_id := v_prefix::UUID;
  ELSIF COALESCE(p_owner_id, '') ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' THEN
    v_target_user_id := p_owner_id::UUID;
  ELSE
    v_target_user_id := auth.uid();
  END IF;

  IF v_actor_user_id IS NULL OR v_target_user_id IS NULL THEN
    RETURN false;
  END IF;
  IF v_target_user_id <> v_actor_user_id
     AND NOT public.get_is_admin() THEN
    RETURN false;
  END IF;

  PERFORM pg_advisory_xact_lock_shared(
    hashtextextended(v_target_user_id::TEXT, 24001)
  );

  SELECT NOT profile.is_blocked INTO v_unblocked
  FROM public.profiles profile
  WHERE profile.id = v_target_user_id;

  RETURN COALESCE(v_unblocked, false);
END;
$$;

REVOKE ALL ON FUNCTION private.lock_deletion_storage_write(TEXT, TEXT)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION private.lock_deletion_storage_write(TEXT, TEXT)
  TO authenticated;

-- Deadlock-freedom invariants for this migration. Every advisory lock below
-- lives in the single `hashtextextended(<uuid>::TEXT, 24001)` keyspace, and:
--
--   (a) Exactly one EXCLUSIVE advisory lock exists in that keyspace: the first
--       statement of public.admin_begin_user_deletion. It is taken before that
--       function acquires any row lock, so it can never be reached while
--       already holding one.
--   (b) Every other lock here is SHARED, so the fences never conflict with one
--       another and their relative order is not load-bearing between them.
--       They are still taken in ascending UUID-text order at each multi-lock
--       site so that a future exclusive locker cannot invert against them.
--   (c) Every fence locks exactly the keys its rejection predicate tests, and
--       nothing else. Locking a key that is not tested would drag ordinary
--       write paths onto the deletion keyspace for no safety benefit and let
--       them deadlock against (a) via the profile row lock. This holds for all
--       three fences: lock_deletion_direct_content_owner locks and tests only
--       the NEW ownership values, lock_deletion_feedback_author locks and tests
--       only NEW.coach_id, and lock_deletion_content_assignment locks exactly
--       the direct-owner set that its predicate then tests.
--
-- This does NOT eliminate the deadlock class. lock_deletion_content_assignment
-- must lock deletion-target keys, because those are precisely the keys it
-- tests. So a transaction that takes a profiles(T) row lock and then performs a
-- fenced assignment write against content owned by T, in the SAME transaction,
-- can still cycle with admin_begin_user_deletion and get 40P01. Operators must
-- keep profile writes and fenced content writes in separate transactions; a
-- 40P01 is retryable and the operation should simply be repeated.

-- Cross-user assignments take the same shared target lock. This prevents an
-- admin save from making directly owned content shared after deletion
-- preflight but before the owner's profile is removed. A workout is directly
-- owned through either `user_id` or `owner_user_id`; both cascade from the
-- owner, so both must be fenced.
CREATE OR REPLACE FUNCTION private.lock_deletion_content_assignment()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_row JSONB := to_jsonb(NEW);
  v_content_id UUID;
  v_assigned_user_id UUID := (v_row->>'user_id')::UUID;
  v_owner_candidates UUID[];
  v_direct_owner_ids UUID[];
  v_direct_owner_id UUID;
BEGIN
  IF TG_TABLE_NAME = 'user_workouts' THEN
    v_content_id := (v_row->>'workout_id')::UUID;
    SELECT ARRAY[workout.user_id, workout.owner_user_id]
    INTO v_owner_candidates
    FROM public.workouts workout
    WHERE workout.id = v_content_id
    FOR SHARE;
  ELSIF TG_TABLE_NAME = 'user_meal_plans' THEN
    v_content_id := (v_row->>'meal_plan_id')::UUID;
    SELECT ARRAY[plan.user_id]
    INTO v_owner_candidates
    FROM public.meal_plans plan
    WHERE plan.id = v_content_id
    FOR SHARE;
  ELSE
    RAISE EXCEPTION 'Unsupported deletion assignment table' USING ERRCODE = '22023';
  END IF;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Assignment parent is not yet visible'
      USING ERRCODE = '40001';
  END IF;

  -- Deduplicate and sort ascending before locking so a workout owned through
  -- both columns locks once and multi-owner rows never invert lock order.
  SELECT array_agg(deduplicated.owner_id ORDER BY deduplicated.owner_id::TEXT)
  INTO v_direct_owner_ids
  FROM (
    SELECT DISTINCT owner_candidate.owner_id
    FROM unnest(v_owner_candidates) AS owner_candidate(owner_id)
    WHERE owner_candidate.owner_id IS NOT NULL
  ) AS deduplicated;

  IF v_direct_owner_ids IS NULL THEN
    RETURN NEW;
  END IF;

  FOREACH v_direct_owner_id IN ARRAY v_direct_owner_ids LOOP
    PERFORM pg_advisory_xact_lock_shared(
      hashtextextended(v_direct_owner_id::TEXT, 24001)
    );
  END LOOP;

  IF EXISTS (
       SELECT 1
       FROM unnest(v_direct_owner_ids) AS direct_owner(owner_id)
       JOIN public.user_deletion_jobs job
         ON job.target_user_id = direct_owner.owner_id
       WHERE direct_owner.owner_id <> v_assigned_user_id
         AND job.status <> 'completed'
     ) THEN
    RAISE EXCEPTION 'Direct content owner has an active deletion job'
      USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.lock_deletion_content_assignment() FROM PUBLIC;

CREATE TRIGGER lock_workout_assignment_during_deletion
BEFORE INSERT OR UPDATE OF user_id, workout_id ON public.user_workouts
FOR EACH ROW EXECUTE FUNCTION private.lock_deletion_content_assignment();

CREATE TRIGGER lock_meal_plan_assignment_during_deletion
BEFORE INSERT OR UPDATE OF user_id, meal_plan_id ON public.user_meal_plans
FOR EACH ROW EXECUTE FUNCTION private.lock_deletion_content_assignment();

-- Owner changes already hold the content row lock before this trigger runs.
-- Direct ownership is carried by `user_id` on both fenced tables and, on
-- public.workouts only, by `owner_user_id`; both columns cascade from
-- auth.users, so both are deletion-relevant. public.meal_plans has no
-- `owner_user_id` column: `to_jsonb(...)->>'owner_user_id'` yields NULL there
-- and the value is discarded as "not present", so the same function serves both
-- triggers.
--
-- Only the NEW ownership values are locked and tested. The OLD values are
-- deliberately NOT locked: a transfer that moves ownership AWAY from a target
-- only makes that target more deletable, so losing that serialization cannot
-- create shared content after preflight. Under MVCC the preflight either sees
-- the pre-transfer row and conservatively flags manual review, or the
-- post-transfer row which no longer references the target; both are safe. Any
-- transfer TOWARD a target is a NEW value and is still locked and tested.
-- Locking the OLD keys would put an ordinary ownership handover — including the
-- remediation this migration's runbook publishes — onto the outgoing athlete's
-- deletion key, where an operator transaction already holding that athlete's
-- profiles row lock could deadlock against admin_begin_user_deletion.
CREATE OR REPLACE FUNCTION private.lock_deletion_direct_content_owner()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_new JSONB := to_jsonb(NEW);
  v_new_user_id UUID := (v_new->>'user_id')::UUID;
  v_new_owner_user_id UUID := (v_new->>'owner_user_id')::UUID;
  v_owner_ids UUID[];
  v_owner_id UUID;
BEGIN
  SELECT array_agg(deduplicated.owner_id ORDER BY deduplicated.owner_id::TEXT)
  INTO v_owner_ids
  FROM (
    SELECT DISTINCT owner_candidate.owner_id
    FROM (
      VALUES
        (v_new_user_id::UUID),
        (v_new_owner_user_id::UUID)
    ) AS owner_candidate(owner_id)
    WHERE owner_candidate.owner_id IS NOT NULL
  ) AS deduplicated;

  IF v_owner_ids IS NOT NULL THEN
    FOREACH v_owner_id IN ARRAY v_owner_ids LOOP
      PERFORM pg_advisory_xact_lock_shared(
        hashtextextended(v_owner_id::TEXT, 24001)
      );
    END LOOP;
  END IF;

  IF EXISTS (
       SELECT 1
       FROM public.user_deletion_jobs job
       WHERE job.status <> 'completed'
         AND (
           job.target_user_id = v_new_user_id
           OR job.target_user_id = v_new_owner_user_id
         )
     ) THEN
    RAISE EXCEPTION 'Direct content owner has an active deletion job'
      USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.lock_deletion_direct_content_owner() FROM PUBLIC;

CREATE TRIGGER lock_workout_owner_during_deletion
BEFORE INSERT OR UPDATE OF user_id, owner_user_id ON public.workouts
FOR EACH ROW EXECUTE FUNCTION private.lock_deletion_direct_content_owner();

CREATE TRIGGER lock_meal_plan_owner_during_deletion
BEFORE INSERT OR UPDATE OF user_id ON public.meal_plans
FOR EACH ROW EXECUTE FUNCTION private.lock_deletion_direct_content_owner();

-- auth.users -> profiles (CASCADE) -> workout_feedback.coach_id (CASCADE)
-- destroys coach feedback the target authored on ANOTHER athlete's training
-- log. Fence new authored rows the same way directly owned content is fenced.
--
-- Exactly one key is locked and tested: NEW.coach_id. Rejection depends solely
-- on that column, so this is a single-lock site and ordering is trivial.
--
-- `NEW.user_id` is deliberately NOT locked. It is the athlete key — the normal
-- deletion target — so locking it would put every ordinary admin feedback write
-- onto the deletion keyspace, where a transaction already holding that
-- athlete's profiles row lock could deadlock against admin_begin_user_deletion
-- (which takes the exclusive advisory lock first and the profile row lock
-- second). `OLD.coach_id` is not locked either: moving authorship AWAY from a
-- target only makes that target more deletable, so losing that serialization
-- cannot create authored content after preflight. Under MVCC the preflight sees
-- either the pre-change row (flags manual review — conservative and safe) or the
-- post-change row (no longer authored by the target — also safe). Authorship
-- moved TOWARD a coach is a NEW value and is still locked and tested.
CREATE OR REPLACE FUNCTION private.lock_deletion_feedback_author()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  PERFORM pg_advisory_xact_lock_shared(
    hashtextextended(NEW.coach_id::TEXT, 24001)
  );

  IF NEW.coach_id <> NEW.user_id
     AND EXISTS (
       SELECT 1 FROM public.user_deletion_jobs job
       WHERE job.target_user_id = NEW.coach_id
         AND job.status <> 'completed'
     ) THEN
    RAISE EXCEPTION 'Feedback author has an active deletion job'
      USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.lock_deletion_feedback_author() FROM PUBLIC;

CREATE TRIGGER lock_workout_feedback_during_deletion
BEFORE INSERT OR UPDATE OF coach_id, user_id ON public.workout_feedback
FOR EACH ROW EXECUTE FUNCTION private.lock_deletion_feedback_author();

-- Auth access tokens can remain valid until expiry after user deletion. These
-- restrictive policies make the profile block effective for the three
-- user-owned buckets before cleanup starts and keep a stale token from
-- recreating objects after the profile/Auth row is gone. Service-role cleanup
-- is not a member of `authenticated` and is unaffected.
CREATE POLICY "Active users read deletion-managed storage"
  ON storage.objects AS RESTRICTIVE FOR SELECT TO authenticated
  USING (
    bucket_id NOT IN ('chat-images', 'check-in-photos', 'meal-photos')
    OR (SELECT public.get_is_admin())
    OR (SELECT private.is_current_user_unblocked())
  );

CREATE POLICY "Active users insert deletion-managed storage"
  ON storage.objects AS RESTRICTIVE FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id NOT IN ('chat-images', 'check-in-photos', 'meal-photos')
    OR private.lock_deletion_storage_write(name, owner_id)
  );

CREATE POLICY "Active users update deletion-managed storage"
  ON storage.objects AS RESTRICTIVE FOR UPDATE TO authenticated
  USING (
    bucket_id NOT IN ('chat-images', 'check-in-photos', 'meal-photos')
    OR private.lock_deletion_storage_write(name, owner_id)
  )
  WITH CHECK (
    bucket_id NOT IN ('chat-images', 'check-in-photos', 'meal-photos')
    OR private.lock_deletion_storage_write(name, owner_id)
  );

CREATE POLICY "Active users delete deletion-managed storage"
  ON storage.objects AS RESTRICTIVE FOR DELETE TO authenticated
  USING (
    bucket_id NOT IN ('chat-images', 'check-in-photos', 'meal-photos')
    OR (SELECT public.get_is_admin())
    OR (SELECT private.is_current_user_unblocked())
  );

-- Service-role-only, invoker-rights RPC. The service role already owns the
-- required table privileges, so no exposed SECURITY DEFINER function is needed.
CREATE OR REPLACE FUNCTION public.admin_begin_user_deletion(
  p_target_user_id UUID,
  p_requested_by UUID
)
RETURNS public.user_deletion_jobs
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_job public.user_deletion_jobs;
  v_target public.profiles;
  v_off_prefix_count BIGINT;
  v_cross_user_request_count BIGINT;
  v_shared_direct_content_count BIGINT;
  v_shared_authored_content_count BIGINT;
BEGIN
  PERFORM pg_advisory_xact_lock(
    hashtextextended(p_target_user_id::TEXT, 24001)
  );

  SELECT * INTO v_job
  FROM public.user_deletion_jobs
  WHERE target_user_id = p_target_user_id
  FOR UPDATE;

  IF FOUND THEN
    IF v_job.status = 'retryable_error' THEN
      UPDATE public.user_deletion_jobs
      SET status = COALESCE(resume_status, 'cleaning_storage'),
          resume_status = NULL,
          last_error_code = NULL,
          last_error_message = NULL,
          lease_token = NULL,
          lease_expires_at = NULL
      WHERE id = v_job.id
      RETURNING * INTO v_job;
    END IF;
    RETURN v_job;
  END IF;

  SELECT * INTO v_target
  FROM public.profiles
  WHERE id = p_target_user_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'User not found' USING ERRCODE = 'P0002';
  END IF;
  IF v_target.is_admin THEN
    RAISE EXCEPTION 'Existing admin accounts cannot be deleted here' USING ERRCODE = '23514';
  END IF;
  IF p_target_user_id = p_requested_by THEN
    RAISE EXCEPTION 'Administrators cannot delete their own account' USING ERRCODE = '23514';
  END IF;

  -- Block before any cleanup work so a partially deleted athlete cannot keep
  -- creating rows or objects while a retry is pending.
  UPDATE public.profiles SET is_blocked = true WHERE id = p_target_user_id;

  SELECT count(*) INTO v_off_prefix_count
  FROM storage.objects
  WHERE bucket_id IN ('chat-images', 'check-in-photos', 'meal-photos')
    AND owner_id = p_target_user_id::text
    AND name <> p_target_user_id::text
    AND name NOT LIKE p_target_user_id::text || '/%';

  -- requested_by is intentionally retained as immutable audit evidence. A
  -- cross-user generation request therefore needs an operator decision before
  -- the target Auth row can be removed.
  SELECT count(*) INTO v_cross_user_request_count
  FROM public.meal_plan_generation_requests
  WHERE requested_by = p_target_user_id
    AND user_id <> p_target_user_id;

  -- A workout is directly owned through either `user_id` or `owner_user_id`;
  -- both cascade from auth.users. One predicate over public.workouts counts a
  -- workout owned through both columns exactly once. A workout is shared when
  -- another user holds an assignment OR when the two ownership columns point
  -- at different users: this migration turns workouts_user_id_fkey into
  -- ON DELETE CASCADE, so a divergently owned workout would otherwise be
  -- destroyed for the other owner without any operator signal.
  -- public.meal_plans has no owner column, so its branch stays keyed on
  -- `plan.user_id`.
  SELECT
    (SELECT count(*)
     FROM public.workouts workout
     WHERE (workout.user_id = p_target_user_id
            OR workout.owner_user_id = p_target_user_id)
       AND (
         EXISTS (
           SELECT 1 FROM public.user_workouts assignment
           WHERE assignment.workout_id = workout.id
             AND assignment.user_id <> p_target_user_id
         )
         OR (workout.user_id IS NOT NULL
             AND workout.user_id <> p_target_user_id)
         OR (workout.owner_user_id IS NOT NULL
             AND workout.owner_user_id <> p_target_user_id)
       ))
    +
    (SELECT count(*)
     FROM public.meal_plans plan
     WHERE plan.user_id = p_target_user_id
       AND EXISTS (
         SELECT 1 FROM public.user_meal_plans assignment
         WHERE assignment.meal_plan_id = plan.id
           AND assignment.user_id <> p_target_user_id
       ))
  INTO v_shared_direct_content_count;

  -- Feedback the target authored on another athlete's log cascades away with
  -- the target's profile, so it needs an operator decision before deletion.
  SELECT count(*) INTO v_shared_authored_content_count
  FROM public.workout_feedback feedback
  WHERE feedback.coach_id = p_target_user_id
    AND feedback.user_id <> p_target_user_id;

  INSERT INTO public.user_deletion_jobs (
    id,
    target_user_id,
    requested_by,
    status,
    last_error_code,
    last_error_message
  ) VALUES (
    p_target_user_id,
    p_target_user_id,
    p_requested_by,
    CASE WHEN v_off_prefix_count > 0
           OR v_cross_user_request_count > 0
           OR v_shared_direct_content_count > 0
           OR v_shared_authored_content_count > 0
      THEN 'manual_review' ELSE 'requested' END,
    CASE
      WHEN v_off_prefix_count > 0 THEN 'off_prefix_storage_objects'
      WHEN v_cross_user_request_count > 0 THEN 'retained_generation_request'
      WHEN v_shared_direct_content_count > 0 THEN 'shared_direct_content'
      WHEN v_shared_authored_content_count > 0 THEN 'shared_authored_content'
      ELSE NULL
    END,
    CASE
      WHEN v_off_prefix_count > 0 THEN 'Target owns storage objects outside the supported user prefix.'
      WHEN v_cross_user_request_count > 0 THEN 'Target requested a meal plan for another user.'
      WHEN v_shared_direct_content_count > 0 THEN 'Target directly owns content assigned to another user.'
      WHEN v_shared_authored_content_count > 0 THEN 'Target authored coach feedback on another user''s training log.'
      ELSE NULL
    END
  ) RETURNING * INTO v_job;

  INSERT INTO public.user_deletion_bucket_progress (job_id, bucket_id)
  VALUES
    (v_job.id, 'chat-images'),
    (v_job.id, 'check-in-photos'),
    (v_job.id, 'meal-photos');

  INSERT INTO public.user_deletion_prefix_work (job_id, bucket_id, prefix, depth)
  VALUES
    (v_job.id, 'chat-images', p_target_user_id::text, 0),
    (v_job.id, 'check-in-photos', p_target_user_id::text, 0),
    (v_job.id, 'meal-photos', p_target_user_id::text, 0);

  RETURN v_job;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_claim_user_deletion(
  p_job_id UUID,
  p_lease_seconds INTEGER DEFAULT 60
)
RETURNS public.user_deletion_jobs
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_job public.user_deletion_jobs;
BEGIN
  IF p_lease_seconds < 15 OR p_lease_seconds > 300 THEN
    RAISE EXCEPTION 'Lease must be between 15 and 300 seconds' USING ERRCODE = '22023';
  END IF;

  UPDATE public.user_deletion_jobs
  SET status = CASE
        WHEN status = 'requested' THEN 'cleaning_storage'
        WHEN status = 'retryable_error' THEN COALESCE(resume_status, 'cleaning_storage')
        ELSE status
      END,
      resume_status = NULL,
      lease_token = gen_random_uuid(),
      lease_expires_at = now() + make_interval(secs => p_lease_seconds),
      attempt_count = attempt_count + 1,
      last_error_code = NULL,
      last_error_message = NULL
  WHERE id = p_job_id
    AND status IN ('requested', 'cleaning_storage', 'deleting_auth', 'retryable_error')
    AND (lease_expires_at IS NULL OR lease_expires_at < now())
  RETURNING * INTO v_job;

  RETURN v_job;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_set_user_deletion_bucket_status(
  p_job_id UUID,
  p_bucket_id TEXT,
  p_status TEXT,
  p_lease_token UUID
)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  IF p_status NOT IN ('cleaning', 'clean') THEN
    RAISE EXCEPTION 'Invalid bucket status' USING ERRCODE = '22023';
  END IF;

  PERFORM 1 FROM public.user_deletion_jobs
  WHERE id = p_job_id
    AND lease_token = p_lease_token
    AND lease_expires_at >= now()
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Deletion job lease is no longer valid' USING ERRCODE = '40001';
  END IF;

  UPDATE public.user_deletion_bucket_progress
  SET status = p_status, updated_at = now()
  WHERE job_id = p_job_id AND bucket_id = p_bucket_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Deletion bucket progress is missing' USING ERRCODE = 'P0002';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_enqueue_user_deletion_prefix(
  p_job_id UUID,
  p_bucket_id TEXT,
  p_prefix TEXT,
  p_depth INTEGER,
  p_lease_token UUID
)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  PERFORM 1 FROM public.user_deletion_jobs
  WHERE id = p_job_id
    AND lease_token = p_lease_token
    AND lease_expires_at >= now()
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Deletion job lease is no longer valid' USING ERRCODE = '40001';
  END IF;

  INSERT INTO public.user_deletion_prefix_work (
    job_id, bucket_id, prefix, depth, status
  ) VALUES (
    p_job_id, p_bucket_id, p_prefix, p_depth, 'pending'
  )
  ON CONFLICT (job_id, bucket_id, prefix) DO NOTHING;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_complete_user_deletion_prefix(
  p_job_id UUID,
  p_prefix_id BIGINT,
  p_lease_token UUID
)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  PERFORM 1 FROM public.user_deletion_jobs
  WHERE id = p_job_id
    AND lease_token = p_lease_token
    AND lease_expires_at >= now()
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Deletion job lease is no longer valid' USING ERRCODE = '40001';
  END IF;

  UPDATE public.user_deletion_prefix_work
  SET status = 'complete', updated_at = now()
  WHERE id = p_prefix_id AND job_id = p_job_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Deletion prefix work is missing' USING ERRCODE = 'P0002';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_record_user_deletion_removed(
  p_job_id UUID,
  p_bucket_id TEXT,
  p_removed_count INTEGER,
  p_lease_token UUID
)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  IF p_removed_count < 0 OR p_removed_count > 100 THEN
    RAISE EXCEPTION 'Removed count must be between 0 and 100' USING ERRCODE = '22023';
  END IF;

  PERFORM 1
  FROM public.user_deletion_jobs
  WHERE id = p_job_id
    AND lease_token = p_lease_token
    AND lease_expires_at >= now()
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Deletion job lease is no longer valid' USING ERRCODE = '40001';
  END IF;

  UPDATE public.user_deletion_bucket_progress
  SET removed_object_count = removed_object_count + p_removed_count,
      updated_at = now()
  WHERE job_id = p_job_id AND bucket_id = p_bucket_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Deletion bucket progress is missing' USING ERRCODE = 'P0002';
  END IF;

  UPDATE public.user_deletion_jobs
  SET removed_object_count = removed_object_count + p_removed_count
  WHERE id = p_job_id;
END;
$$;

-- Repeat the ownership/reference preflight immediately before Auth deletion.
-- The first preflight occurs after the profile is blocked; this second check
-- also catches an upload transaction that was already in flight at that time.
CREATE OR REPLACE FUNCTION public.admin_preflight_user_deletion(
  p_job_id UUID,
  p_lease_token UUID
)
RETURNS TABLE (ready BOOLEAN, next_status TEXT, error_code TEXT)
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_target_user_id UUID;
  v_off_prefix_count BIGINT;
  v_in_prefix_count BIGINT;
  v_cross_user_request_count BIGINT;
  v_shared_direct_content_count BIGINT;
  v_shared_authored_content_count BIGINT;
  v_error_code TEXT;
  v_error_message TEXT;
BEGIN
  SELECT target_user_id INTO v_target_user_id
  FROM public.user_deletion_jobs
  WHERE id = p_job_id
    AND lease_token = p_lease_token
    AND lease_expires_at >= now()
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Deletion job lease is no longer valid' USING ERRCODE = '40001';
  END IF;

  SELECT count(*) INTO v_off_prefix_count
  FROM storage.objects
  WHERE bucket_id IN ('chat-images', 'check-in-photos', 'meal-photos')
    AND owner_id = v_target_user_id::text
    AND name <> v_target_user_id::text
    AND name NOT LIKE v_target_user_id::text || '/%';

  SELECT count(*) INTO v_in_prefix_count
  FROM storage.objects
  WHERE bucket_id IN ('chat-images', 'check-in-photos', 'meal-photos')
    AND (
      name = v_target_user_id::text
      OR name LIKE v_target_user_id::text || '/%'
    );

  SELECT count(*) INTO v_cross_user_request_count
  FROM public.meal_plan_generation_requests
  WHERE requested_by = v_target_user_id
    AND user_id <> v_target_user_id;

  SELECT
    (SELECT count(*)
     FROM public.workouts workout
     WHERE (workout.user_id = v_target_user_id
            OR workout.owner_user_id = v_target_user_id)
       AND (
         EXISTS (
           SELECT 1 FROM public.user_workouts assignment
           WHERE assignment.workout_id = workout.id
             AND assignment.user_id <> v_target_user_id
         )
         OR (workout.user_id IS NOT NULL
             AND workout.user_id <> v_target_user_id)
         OR (workout.owner_user_id IS NOT NULL
             AND workout.owner_user_id <> v_target_user_id)
       ))
    +
    (SELECT count(*)
     FROM public.meal_plans plan
     WHERE plan.user_id = v_target_user_id
       AND EXISTS (
         SELECT 1 FROM public.user_meal_plans assignment
         WHERE assignment.meal_plan_id = plan.id
           AND assignment.user_id <> v_target_user_id
       ))
  INTO v_shared_direct_content_count;

  SELECT count(*) INTO v_shared_authored_content_count
  FROM public.workout_feedback feedback
  WHERE feedback.coach_id = v_target_user_id
    AND feedback.user_id <> v_target_user_id;

  IF v_off_prefix_count > 0
     OR v_cross_user_request_count > 0
     OR v_shared_direct_content_count > 0
     OR v_shared_authored_content_count > 0 THEN
    v_error_code := CASE
      WHEN v_off_prefix_count > 0 THEN 'off_prefix_storage_objects'
      WHEN v_cross_user_request_count > 0 THEN 'retained_generation_request'
      WHEN v_shared_direct_content_count > 0 THEN 'shared_direct_content'
      WHEN v_shared_authored_content_count > 0 THEN 'shared_authored_content'
      ELSE NULL
    END;
    v_error_message := CASE
      WHEN v_off_prefix_count > 0 THEN 'Target owns storage objects outside the supported user prefix.'
      WHEN v_cross_user_request_count > 0 THEN 'Target requested a meal plan for another user.'
      WHEN v_shared_direct_content_count > 0 THEN 'Target directly owns content assigned to another user.'
      WHEN v_shared_authored_content_count > 0 THEN 'Target authored coach feedback on another user''s training log.'
      ELSE NULL
    END;

    UPDATE public.user_deletion_jobs
    SET status = 'manual_review',
        resume_status = NULL,
        lease_token = NULL,
        lease_expires_at = NULL,
        last_error_code = v_error_code,
        last_error_message = v_error_message
    WHERE id = p_job_id;

    RETURN QUERY SELECT false, 'manual_review'::TEXT, v_error_code;
    RETURN;
  END IF;

  IF v_in_prefix_count > 0 THEN
    UPDATE public.user_deletion_bucket_progress
    SET status = 'pending', updated_at = now()
    WHERE job_id = p_job_id;

    UPDATE public.user_deletion_prefix_work
    SET status = 'pending', updated_at = now()
    WHERE job_id = p_job_id;

    INSERT INTO public.user_deletion_prefix_work (
      job_id, bucket_id, prefix, depth, status
    )
    SELECT p_job_id, bucket_id, v_target_user_id::TEXT, 0, 'pending'
    FROM public.user_deletion_bucket_progress
    WHERE job_id = p_job_id
    ON CONFLICT (job_id, bucket_id, prefix)
    DO UPDATE SET status = 'pending', updated_at = now();

    UPDATE public.user_deletion_jobs
    SET status = 'cleaning_storage',
        resume_status = NULL,
        lease_token = NULL,
        lease_expires_at = NULL,
        last_error_code = 'in_prefix_storage_objects',
        last_error_message = 'Storage changed during deletion; cleanup must run again.'
    WHERE id = p_job_id;

    RETURN QUERY SELECT false, 'cleaning_storage'::TEXT, 'in_prefix_storage_objects'::TEXT;
    RETURN;
  END IF;

  RETURN QUERY SELECT true, 'deleting_auth'::TEXT, NULL::TEXT;
END;
$$;

-- Explicit operator recheck for a manual-review job. Calling this RPC does not
-- bypass either safety condition; it only resumes after the operator has
-- resolved the offending object/reference. The Edge handler records the
-- associated attempt and terminal audit event with the operator request id.
CREATE OR REPLACE FUNCTION public.admin_recheck_user_deletion_manual_review(
  p_job_id UUID
)
RETURNS public.user_deletion_jobs
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_job public.user_deletion_jobs;
  v_off_prefix_count BIGINT;
  v_cross_user_request_count BIGINT;
  v_shared_direct_content_count BIGINT;
  v_shared_authored_content_count BIGINT;
BEGIN
  SELECT * INTO v_job
  FROM public.user_deletion_jobs
  WHERE id = p_job_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Deletion job not found' USING ERRCODE = 'P0002';
  END IF;
  IF v_job.status <> 'manual_review' THEN
    RETURN v_job;
  END IF;

  SELECT count(*) INTO v_off_prefix_count
  FROM storage.objects
  WHERE bucket_id IN ('chat-images', 'check-in-photos', 'meal-photos')
    AND owner_id = v_job.target_user_id::text
    AND name <> v_job.target_user_id::text
    AND name NOT LIKE v_job.target_user_id::text || '/%';

  SELECT count(*) INTO v_cross_user_request_count
  FROM public.meal_plan_generation_requests
  WHERE requested_by = v_job.target_user_id
    AND user_id <> v_job.target_user_id;

  SELECT
    (SELECT count(*)
     FROM public.workouts workout
     WHERE (workout.user_id = v_job.target_user_id
            OR workout.owner_user_id = v_job.target_user_id)
       AND (
         EXISTS (
           SELECT 1 FROM public.user_workouts assignment
           WHERE assignment.workout_id = workout.id
             AND assignment.user_id <> v_job.target_user_id
         )
         OR (workout.user_id IS NOT NULL
             AND workout.user_id <> v_job.target_user_id)
         OR (workout.owner_user_id IS NOT NULL
             AND workout.owner_user_id <> v_job.target_user_id)
       ))
    +
    (SELECT count(*)
     FROM public.meal_plans plan
     WHERE plan.user_id = v_job.target_user_id
       AND EXISTS (
         SELECT 1 FROM public.user_meal_plans assignment
         WHERE assignment.meal_plan_id = plan.id
           AND assignment.user_id <> v_job.target_user_id
       ))
  INTO v_shared_direct_content_count;

  SELECT count(*) INTO v_shared_authored_content_count
  FROM public.workout_feedback feedback
  WHERE feedback.coach_id = v_job.target_user_id
    AND feedback.user_id <> v_job.target_user_id;

  IF v_off_prefix_count = 0
     AND v_cross_user_request_count = 0
     AND v_shared_direct_content_count = 0
     AND v_shared_authored_content_count = 0 THEN
    UPDATE public.user_deletion_jobs
    SET status = 'cleaning_storage',
        resume_status = NULL,
        lease_token = NULL,
        lease_expires_at = NULL,
        last_error_code = NULL,
        last_error_message = NULL
    WHERE id = p_job_id
    RETURNING * INTO v_job;
    RETURN v_job;
  END IF;

  UPDATE public.user_deletion_jobs
  SET last_error_code = CASE
        WHEN v_off_prefix_count > 0 THEN 'off_prefix_storage_objects'
        WHEN v_cross_user_request_count > 0 THEN 'retained_generation_request'
        WHEN v_shared_direct_content_count > 0 THEN 'shared_direct_content'
        WHEN v_shared_authored_content_count > 0 THEN 'shared_authored_content'
        ELSE NULL
      END,
      last_error_message = CASE
        WHEN v_off_prefix_count > 0 THEN 'Target owns storage objects outside the supported user prefix.'
        WHEN v_cross_user_request_count > 0 THEN 'Target requested a meal plan for another user.'
        WHEN v_shared_direct_content_count > 0 THEN 'Target directly owns content assigned to another user.'
        WHEN v_shared_authored_content_count > 0 THEN 'Target authored coach feedback on another user''s training log.'
        ELSE NULL
      END
  WHERE id = p_job_id
  RETURNING * INTO v_job;

  RETURN v_job;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_begin_user_deletion(UUID, UUID)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.admin_claim_user_deletion(UUID, INTEGER)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.admin_set_user_deletion_bucket_status(UUID, TEXT, TEXT, UUID)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.admin_enqueue_user_deletion_prefix(UUID, TEXT, TEXT, INTEGER, UUID)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.admin_complete_user_deletion_prefix(UUID, BIGINT, UUID)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.admin_record_user_deletion_removed(UUID, TEXT, INTEGER, UUID)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.admin_preflight_user_deletion(UUID, UUID)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.admin_recheck_user_deletion_manual_review(UUID)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_begin_user_deletion(UUID, UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_claim_user_deletion(UUID, INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_set_user_deletion_bucket_status(UUID, TEXT, TEXT, UUID)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_enqueue_user_deletion_prefix(UUID, TEXT, TEXT, INTEGER, UUID)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_complete_user_deletion_prefix(UUID, BIGINT, UUID)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_record_user_deletion_removed(UUID, TEXT, INTEGER, UUID)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_preflight_user_deletion(UUID, UUID)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_recheck_user_deletion_manual_review(UUID)
  TO service_role;

-- Auth deletion should not be blocked by nullable ownership/audit fields.
ALTER TABLE public.workouts
  DROP CONSTRAINT IF EXISTS workouts_user_id_fkey,
  ADD CONSTRAINT workouts_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE,
  DROP CONSTRAINT IF EXISTS workouts_coach_id_fkey,
  ADD CONSTRAINT workouts_coach_id_fkey
    FOREIGN KEY (coach_id) REFERENCES auth.users(id) ON DELETE SET NULL;

ALTER TABLE public.meal_plans
  DROP CONSTRAINT IF EXISTS meal_plans_user_id_fkey,
  ADD CONSTRAINT meal_plans_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE,
  DROP CONSTRAINT IF EXISTS meal_plans_coach_id_fkey,
  ADD CONSTRAINT meal_plans_coach_id_fkey
    FOREIGN KEY (coach_id) REFERENCES auth.users(id) ON DELETE SET NULL;

ALTER TABLE public.nutrition_targets
  DROP CONSTRAINT IF EXISTS nutrition_targets_created_by_fkey,
  ADD CONSTRAINT nutrition_targets_created_by_fkey
    FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
